sequenceDiagram
    participant IC as Institutional Client
    participant JPM
    participant TFA as Treasury/Fund Acct
    participant GCS as Global Cash Services
    participant TA

    %% Purchase Flow
    IC->>JPM: Initiates fed wire for purchase
    JPM->>GCS: Receives fed wire in clearing acct
    GCS->>TA: Creates pega case upon receipt of wire
    TA->>TFA: Reconciles transaction with wired funds received
    TFA->>JPM: Initiates wire from clearing to fund acct
    JPM-->>JPM: Receives wire into Fund Account

    %% Liquidation Flow
    TA->>GCS: Creates pega case for outgoing wire
    GCS->>TFA: Initiates wire to the client
    TFA->>JPM: Initiates wire from Fund acct to Clearing Acct
    JPM->>JPM: Fund Acct wires to clearing account
    JPM->>IC: Clearing Acct wires to client
    IC-->>IC: Receives wire
