graph TD
  MakerDAO --> |USDC| DOP[Dinari Order Processor]
  DOP --> |USFR.d| MakerDAO
  DOP --> |USDC| Circle
  DOP -.-> |Order| AB[Alpaca Brokerage]
  DOP -.-> |Order Fill| AB
  
  Circle --> |USD Fedwire| MB[Mercury Bank]
  DOP --> |USDC| AB[Alpaca Brokerage]
  
  MB --> |USD Fedwire| AB
  AB --> USFR