%%{init: {"flowchart": {"htmlLabels": true}}}%%
flowchart LR
    Securities[<div style="width:200px; height:50px; display:flex; align-items:center; justify-content:center;">SHORT-DURATION US GOVERNMENT SECURITIES</div>]
    USDX[<div style="height:50px; display:flex; align-items:center; justify-content:center;">USDX</div>]
    Investor[<div style="height:50px; display:flex; align-items:center; justify-content:center;">INVESTOR</div>]
    Securities -->|CASH FLOW| USDX
    USDX -->|DIVIDEND YIELD| Investor