graph TD
    HUB[Municipal Bond Fund] --> SPOKES[Share Classes]
    SPOKES --> MF[Mutual Fund]
    SPOKES --> TKN[Token]
    SPOKES --> ETF[ETF]
    TKN --> USDX[USDX<br>Rebase]
    TKN --> USDXW[USDXW<br>Accum]